server:
  port: 8080 

spring:
  application:
    name: recognition-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}      
    port: 5672
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    # 🟢 NOVO: Habilita a interceptação do Micrometer Tracing no RabbitMQ
    listener:
      simple:
        observation-enabled: true
    template:
      observation-enabled: true
    queues:
      raw-tracking: ${VISION_QUEUE_NAME:safevision.vision.raw.tracking} 
      alerts: ${ALERTS_QUEUE_NAME:safevision.alerts}

# --- CONFIGURAÇÃO ZIPKIN E METRICAS ---
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  tracing:
    sampling:
      probability: 1.0 
    propagation:
      type: B3_MULTI # Fundamental: Lê os headers X-B3-* injetados na mensagem do RabbitMQ pelo Python
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

safevision:
  services:
    alert: ${SAFEVISION_SERVICES_ALERT:http://alert-service:8080}
  jwt:
    secret: ${SAFEVISION_JWT_SECRET:segredo_padrao_apenas_para_desenvolvimento_local_sem_docker}

logging:
  file:
    name: /var/logs/${spring.application.name}.log 
  pattern:
    # Injeta o traceId e spanId no console e no arquivo para validação visual fim-a-fim
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}[traceId=%X{traceId:-}, spanId=%X{spanId:-}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}[traceId=%X{traceId:-}, spanId=%X{spanId:-}] - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
  level:
    root: INFO
    com.safevision: DEBUG 
    org.springframework.amqp: INFO